// =================================================================
// Jenkinsfile  —  generated by DevOps Pipeline Platform
// App: test-repo  |  Type: python
// =================================================================
pipeline {
  agent any

  options {
    buildDiscarder(logRotator(numToKeepStr: '20'))
    timeout(time: 60, unit: 'MINUTES')
  }

  environment {
    APP_NAME    = 'test-repo'
    APP_VERSION = '1.0.0'
  }

  // push / pull_request: configure an SCM webhook on the repo to trigger builds,
  // or add  triggers { pollSCM('H/5 * * * *') }  to poll for changes instead.

  stages {
    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/witslab-sahil/test-repo.git', credentialsId: 'git-npci-creds'
      }
    }
    stage('Build') {
      steps {
        sh '''
        docker run --rm \
        --volumes-from jenkins-10 \
        -w "$PWD" \
        python:3.11 \
        sh onboarding/ci/build/default-build.sh
        '''
      }
    }
    stage('Test') {
      steps {
        // Coverage gate: 80% (enforced inside the test script)
        sh '''
        docker run --rm \
        --volumes-from jenkins-10 \
        -w "$PWD" \
        python:3.11 \
        sh onboarding/ci/test/default-test.sh
        '''
      }
    }
    stage('SonarQube Analysis') {
      when { expression { return false } }
      steps {
        echo 'Stage disabled by platform config (ci.scan.*.enabled=false) — skipped.'
      }
    }
    stage('Checkmarx SAST') {
      when { expression { return false } }
      steps {
        echo 'Stage disabled by platform config (ci.scan.*.enabled=false) — skipped.'
      }
    }
    stage('Architecture-as-Code') {
      when { expression { return false } }
      steps {
        echo 'Stage disabled by platform config (ci.scan.*.enabled=false) — skipped.'
      }
    }
  }

  post {
    success {
      mail to: 'sahil.sharma_wit@npci.org.in', subject: "✅ ${APP_NAME} #${BUILD_NUMBER} passed", body: "${BUILD_URL}"
    }
    failure {
      mail to: 'sahil.sharma_wit@npci.org.in', subject: "❌ ${APP_NAME} #${BUILD_NUMBER} failed", body: "${BUILD_URL}"
    }
    always {
      echo "Pipeline finished with status: ${currentBuild.currentResult}"
    }
  }
}
